version: '3.8'

services:
  bot:
    image: getkarma/discord-bot-private:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: discord_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/app/data
    user: "10001:10001"
    restart: unless-stopped
    container_name: karma-private-bot

  db:
    image: postgres:13
    container_name: db_bot
    env_file:
      - .env  # Load environment variables from stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
