version: "3"
services:
  discord-bot-private:
    image: getkarma/discord-bot-private:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/karma/docker/Bot/Discord_Bot_Private:/app
