version: '3'
services:
  bot:
    image: getkarma/discord-bot-private:latest
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    