name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'bot.py'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'data/*'
      - 'requirements.txt'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: getkarma/discord-bot-private:latest
        build-args: |
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }}
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    - name: Run Docker Compose
      run: |
        docker-compose up -d